---
title: "hw5"
author: "Anna Sorokina"
editor_options: 
  chunk_output_type: console
---

### 5.1
```{r}
library(tidyverse)
library(ca)
chairs <- read.csv("https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/ansorox/hw5_CA_MCA/hw5_chairs.csv")
rm.cols <- c("Shop", "WordDE", "Category") # ненужные переменные
chairs2 <- chairs[, ! names(chairs) %in% rm.cols, drop = F] # создаем датасет, в котором нет ненужных переменных

MCA <- MASS::mca(chairs2) # строим МСА
chairs <- cbind(chairs, MCA$rs)
vars <- as_data_frame(MCA$cs)
vars$var_names <- rownames(MCA$cs)

chairs %>%
  ggplot(aes(`1`, `2`))+
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = vars, aes(`1`, `2`, label = var_names))+
  theme_light()+
  scale_x_continuous(limits = c(-0.025, 0.02))

```
### 5.2
```{r}
Sessel и Stuhl хорошо различаются по ряду признаков: наличию дополнительной функции (Sessel может иметь функцию кровати (AddFunctions.Bed), Stuhl скорее не имеет дополнительных функций (AddFunctions.No)), наличию подлокотников (Sessel - Arms.Yes, Stuhl - Arms.No), материалу (Sessel - MaterialSeat.Leather, MaterialSeat.Fabric; Shuhl - MaterialSeat.Steel, MaterialSeat.Plastic, MaterialSeat.Paper), возможности откидывать спинку (Sessel - ReclineBack.Yes, Stuhl - ReclineBack.No), назначению (Sessel - Function.Relax; Stuhl - Function.Eat, Function.Outdoor, Function.NotSpec).
Тем не менее, категории Sessel и Stuhl пересекаются по ряду признаков. 

```
### 5.3
```{r}
colreg <- read.csv("https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/ansorox/hw5_CA_MCA/hw5_colreg.csv")

rownames(colreg) <- colreg$colors
ca <- ca(colreg[, -5])

colreg_c <- data.frame(ca$colcoord)
colreg_c$rows <- rownames(ca$colcoord)

colreg_r <- data.frame(ca$rowcoord)
colreg_r$rows <- rownames(ca$rowcoord)

colreg_c %>%
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "darkgreen")+
  geom_text(data = colreg_r, color = "darkgrey")+
  theme_light()

```
### 5.4

```{r}
Для художественных текстов и прессы характерно использование большого количества обозначений цветов. Цвета наиболее часто встречающиеся в художественных текстах - желтый, голубой, розовый, фиолетовый, коричневый. В прессе - зеленый, оранжевый, красный. В устных текстах - черный. Белый примерно одинаково часто встречается в устных, художественных и академических текстах. 
В текстах академического подкорпуса почти не встречается обозначений цветов. 

```
